### ISSUE TITLE
Packaging sample does not run on JDK11

### ISSUE THREAD

**Issue by JochenHiller** [eclipse/smarthome-packaging-sample#25]
See Concierge issue https://github.com/eclipse/concierge/issues/67: slf4j-jdk14 bundle can not be installed in JDK11

```
Concierge> Exception in thread "main" org.osgi.framework.BundleException: Framework does not support extensions
	at org.eclipse.concierge.compat.service.BundleManifestTwo.processManifest(BundleManifestTwo.java:227)
	at org.eclipse.concierge.BundleImpl$Revision.<init>(BundleImpl.java:1579)
	at org.eclipse.concierge.BundleImpl$JarBundleRevision.<init>(BundleImpl.java:3587)
	at org.eclipse.concierge.BundleImpl.readAndProcessInputStream(BundleImpl.java:395)
	at org.eclipse.concierge.BundleImpl.<init>(BundleImpl.java:225)
	at org.eclipse.concierge.Concierge.installNewBundle(Concierge.java:4078)
	at org.eclipse.concierge.Concierge.installNewBundle(Concierge.java:4041)
	at org.eclipse.concierge.Concierge$BundleContextImpl.installBundle(Concierge.java:4662)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsInputStream(XargsFileLauncher.java:189)
	at org.eclipse.concierge.compat.service.XargsFileLauncher.processXargsFile(XargsFileLauncher.java:83)
	at org.eclipse.concierge.Concierge.doMain(Concierge.java:606)
	at org.eclipse.concierge.Concierge.main(Concierge.java:525)
```

**Comment by tmarkwardt** [comment]
on java 11 the default class loader was changed from URLClassLoader to AppClassLoader (
jdk.internal.loader.ClassLoaders.AppClassloaders, jdk.internal.loader.BuiltinClassLoader, java.security.ClassLoader, ...). The code in Concierge.java, line 939..952 checked the ClassLoader from Concierge framework on URLClassLoader. When Concierge don't loaded with URLClassLoader, here stopped the startup from concierge ...

a idea to change?
